# Generated by Django 4.1 on 2022-09-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assesment',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
    ]
